---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: "devhblimageregistry.azurecr.io/frontendadmin:~4353"
    argocd-image-updater.argoproj.io/write-back-method: "git:secret:argocd/argocd-startsml"
    argocd-image-updater.argoproj.io/frontendadmin.pull-secret: "secret:argocd/acr-secret"
    argocd-image-updater.argoproj.io/git-branch: "main"
    notifications.argoproj.io/subscribe.on-deleted.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-deployed.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-sync-failed.slace: argo-notifications
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo-notifications
spec:
  project: dev
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: helm/inficare
    repoURL: "https://github.com/startsml/argo_startlocal.git"
    targetRevision: main
    helm:
      values: |
        namespace: dev
        image:
          repository: devhblimageregistry.azurecr.io/frontendadmin
          tag: 4353
          private: true
          secretref: acr-secret
        containers:
          ports:
            http:
              name: http
              containerPort: 3000
              protocol: TCP
        readinessProbe:
          port: 3000
        livenessProbe:
          port: 3000
        ingress:
          enabled: true
          className: ingress-external
          hosts:
            - host: hbl-admin.iremit.com.my
              paths:
                - path: /
                  pathType: ImplementationSpecific
        service:
          name: frontend-dev
        serviceAccount:
          name: frontend-dev-sa
        podSecurityContext:
          enabled: true
          fsGroup: 1000
        containerSecurityContext:
          enabled: true
          runAsUser: 1000
          runAsNonRoot: true
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: "RuntimeDefault"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/worker
                      operator: Exists
        app:
          vault: false
          name: frontend
          env: dev
          cert: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
