---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: devhblimageregistry.azurecr.io/frontendadmin:~4353
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-startsml
    argocd-image-updater.argoproj.io/frontendadmin.pull-secret: secret:argocd/acr-secret
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: dev
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: helm/inficare
    repoURL: "https://github.com/startsml/argo_startlocal.git"
    targetRevision: main
    helm:
      valueFiles:       # Specify the path to values files if any
        - frontendvalues.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
