---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: "identityservice=devhblimageregistry.azurecr.io/identityservice"
    argocd-image-updater.argoproj.io/identityservice.allow-tags: regexp:^main-([0-9]{10})-([a-f0-9]{7})
    argocd-image-updater.argoproj.io/write-back-method: "git:secret:argocd/argocd-startsml"
    argocd-image-updater.argoproj.io/identityservice.pull-secret: "secret:argocd/acr-secret"
    argocd-image-updater.argoproj.io/identityservice.update-strategy: name
    argocd-image-updater.argoproj.io/git-branch: "main"
    notifications.argoproj.io/subscribe.on-deleted.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-deployed.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-sync-failed.slace: argo-notifications
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo-notifications
spec:
  project: dev
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: helm/inficare
    repoURL: "https://github.com/startsml/argo_startlocal.git"
    targetRevision: main
    helm:
      values: |
        namespace: dev
        image:
          repository: devhblimageregistry.azurecr.io/identityservice
          tag: main-1727361340-46a0e84
          private: true
          secretref: acr-secret
        containers:
          ports:
            http:
              name: http
              containerPort: 8080
              protocol: TCP
        readinessProbe:
          type: tcpSocket
          tcpSocket:
            port: 8080
        livenessProbe:
          type: tcpSocket
          tcpSocket:
            port: 8080
        ingress:
          enabled: true
          className: ingress-external
          hosts:
            - host: hbl-admin.startlocal
              paths:
                - path: /identity
                  pathType: Prefix
        podSecurityContext:
          enabled: true
          fsGroup: 1000
        containerSecurityContext:
          enabled: true
          runAsUser: 1000
          runAsNonRoot: true
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: "RuntimeDefault"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/worker
                      operator: Exists
        app:
          vault: false
          name: identity
          env: dev
          cert: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
