---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-issuer-setup
  namespace: argocd  # Change to your ArgoCD namespace
spec:
  project: infra  # ArgoCD project, use default or your custom project name
  source:
    repoURL: https://github.com/startsml/argo_startlocal.git
    targetRevision: HEAD  # Use the branch name or tag where your manifests are
    path: argocd/infra/cert/manifests  # Path to the directory in the Git repo containing the YAML files
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager  # Where the resources will be deployed
  syncPolicy:
    automated:
      prune: true  # Automatically remove resources that are no longer tracked in Git
      selfHeal: true  # Automatically apply changes if drift occurs
    syncOptions:
      - CreateNamespace=true  # Automatically create the namespace if it doesn't exist
