---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: startsml-app
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Start Small App Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  # Only permit applications to deploy to the namespace in the same cluster
  destinations:
    - server: https://kubernetes.default.svc
      name: in-cluster
      namespace: startsml-dev
    - server: https://kubernetes.default.svc
      name: in-cluster
      namespace: startsml-stg
    - server: https://kubernetes.default.svc
      name: in-cluster
      namespace: startsml-prod
    - server: https://kubernetes.default.svc
      name: in-cluster
      namespace: istio-system
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
