project: monitor
source:
  repoURL: "https://k3rnelpan1c-dev.github.io/uptime-kuma-helm/"
  targetRevision: 1.3.3
  helm:
    values: |-

      persistence:
        enabled: true
        storageClass: longhorn
      podSecurityContext:
        fsGroup: 1000
        seccompProfile:
          type: "RuntimeDefault"
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        privileged: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: "RuntimeDefault"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
  chart: uptime-kuma
destination:
  server: "https://kubernetes.default.svc"
  namespace: monitor
syncPolicy:
  automated: {}
