---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontendadmin-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: "frontendadmin=devhblimageregistry.azurecr.io/frontendadmin"
    argocd-image-updater.argoproj.io/frontendadmin.allow-tags: regexp:^main-([0-9]{10})-([a-f0-9]{7})
    argocd-image-updater.argoproj.io/write-back-method: "git:secret:argocd/argocd-startsml"
    argocd-image-updater.argoproj.io/frontendadmin.pull-secret: "secret:argocd/acr-secret"
    argocd-image-updater.argoproj.io/frontendadmin.update-strategy: name
    argocd-image-updater.argoproj.io/git-branch: "main"
    notifications.argoproj.io/subscribe.on-deleted.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-created.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-deployed.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo-notifications
    notifications.argoproj.io/subscribe.on-deleted.googlechat: spaceName
    notifications.argoproj.io/subscribe.on-created.googlechat: spaceName
    notifications.argoproj.io/subscribe.on-deployed.googlechat: spaceName
    notifications.argoproj.io/subscribe.on-health-degraded.googlechat: spaceName
    notifications.argoproj.io/subscribe.on-sync-failed.googlechat: spaceName
    notifications.argoproj.io/subscribe.on-sync-status-unknown.googlechat: spaceName
    notifications.argoproj.io/subscribe.on-sync-succeeded.googlechat: spaceName
spec:
  project: dev
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: helm/inficare
    repoURL: "https://github.com/startsml/argo_startlocal.git"
    targetRevision: main
    helm:
      values: |
        namespace: dev
        image:
          repository: devhblimageregistry.azurecr.io/frontendadmin
          tag: main-1732094705-9338580
          private: true
          secretref: acr-secret
        containers:
          ports:
            http:
              name: http
              containerPort: 3000
              protocol: TCP
        readinessProbe:
          httpGet:
            port: 3000
        livenessProbe:
          httpGet:
            port: 3000
        ingress:
          enabled: true
          className: ingress-external
          hosts:
            - host: hbl-admin.iremit.com.my
              paths:
                - path: /
                  pathType: ImplementationSpecific
                - path: /identity
                  pathType: Prefix
                  servicename: identity
                - path: /transaction
                  pathType: Prefix
                  servicename: transaction
        podSecurityContext:
          fsGroup: 1001
          seccompProfile:
            type: RuntimeDefault
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: "RuntimeDefault"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/worker
                      operator: Exists
        app:
          vault: true
          name: frontendadmin
          env: dev
          cert: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
