apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-python-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/shahgnp/demo-python-app:~v0.1
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  destination:
    namespace: demo-python-app
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/demo-python-app
    repoURL: 'https://github.com/startsml/argo_startlocal.git'
    targetRevision: HEAD
  project: demo-python-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
