apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-python-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/shahgnp/demo-python-app:~v0.1
spec:
  destination:
    namespace: demo-python-app
    server: 'https://kubernetes.default.svc'
  source:
    path: demo-python-app
    repoURL: 'https://github.com/startsml/helm_startlocal.git'
    targetRevision: HEAD
    values: |
      auth:
        existingSecret: helm-startsml
  project: demo-python-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
