apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/master/manifests/install.yaml
  - infra/project.yaml
  - infra/app.yaml
  - redis/project.yaml
  - redis/app.yaml
  - app/project.yaml
