---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: redis
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.6.1
    helm:
      # Release name override (defaults to application name)
      releaseName: redis
      values: |
        enabled: true
        global:
          storageClass: longhorn
        master:
          persistence:
            storageClass: longhorn
            size: 5Gi
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/worker
                        operator: Exists
          podSecurityContext:
            seccompProfile:
              type: RuntimeDefault
        replica:
          persistence:
            storageClass: longhorn
            size: 5Gi
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/worker
                        operator: Exists
          podSecurityContext:
            seccompProfile:
              type: RuntimeDefault
        auth:
          existingSecret: redis-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
